/* eslint-disable linebreak-style */
const data = {
  'otp click': {
    linkType: 'button',
    StepName: 'Identify Yourself',
    linkPosition: 'Form',
  },
  'privacy consent click': {
    linkType: 'checkbox',
    StepName: 'Identify Yourself',
    linkPosition: 'Form',
  },
  'submit otp click': {
    linkType: 'button',
    StepName: 'OTP Verification',
    linkPosition: 'Form',
  },
  'resend otp click': {
    linkType: 'button',
    StepName: 'Resend OTP',
    linkPosition: 'Form',
  },
  'select account type click': {
    linkType: 'button',
    StepName: 'Select Account Type',
    linkPosition: 'Form',
  },
  'continue btn select account': {
    linkType: 'button',
    StepName: 'Select Account',
    linkPosition: 'Form',
  },
  'confirm details click': {
    linkType: 'button',
    StepName: 'Confirm Details',
    linkPosition: 'Form',
  },
  'thankyou page click': {
    linkType: 'button',
    StepName: 'Confirm Details',
    linkPosition: 'Form',
  },
  'idcom redirection check': {
    linkType: 'button',
    StepName: 'IDCOM Redirection',
    linkPosition: 'Form',
  },
  'HDFC Bank Website Link Click': {
    linkType: 'link',
    StepName: 'Clicked HDFC Bank Website Link',
    linkPosition: 'Form',
  },
  'Apply for a CTA Click': {
    linkType: 'link',
    StepName: 'Clicked HDFC Bank Website Link',
    linkPosition: 'Form',
  },
  'nine_rating_cta_click': {
    linkType: 'link',
    StepName: 'Nine Rating CTA Clicked',
    linkPosition: 'Form',
  },
  'ten_rating_cta_click': {
    linkType: 'link',
    StepName: 'Ten Rating CTA Clicked',
    linkPosition: 'Form',
  },
  'submit otp': {
    error: '',
  },
  'check offers': {
    linkType: 'button',
    linkName: 'Check Offers',
    linkPosition: 'Form',
  },
  'get this card': {
    linkType: 'button',
    linkName: 'Get this Card',
    linkPosition: 'Form',
  },
  'i agree': {
    linkType: 'button',
    linkName: 'I agree',
    linkPosition: 'Form',
  },
  'document upload continue': {
    linkType: 'button',
    linkName: 'I agree',
    linkPosition: 'Form',
  },
  'address continue': {
    linkType: 'button',
    linkName: 'Submit',
    linkPosition: 'Form',
  },
  'kyc continue': {
    linkType: 'button',
    linkName: 'Continue KYC',
    linkPosition: 'Form',
  },
  // 'aadhaar otp': {
  //   linkType: '',
  //   linkName: '',
  // },
  'start kyc': {
    linkType: 'button',
    linkName: 'Start KYC',
    linkPosition: 'Form',
  },
  'submit review': {
    linkType: 'button',
    linkName: 'Submit Feedback',
    linkPosition: 'Form',
  },
  'accordion click': {
    linkType: 'accordion',
    StepName: 'Confirm Details',
    linkPosition: 'Form',
  },
  'Fatca Details accordion collapse click': {
    linkType: 'accordion',
    linkName: 'Fatca Details Accordion Collapse',
    StepName: 'Confirm Details',
    linkPosition: 'Form',
  },
  'Fatca Details accordion expand click': {
    linkType: 'accordion',
    linkName: 'Fatca Details Accordion Expand',
    StepName: 'Confirm Details',
    linkPosition: 'Form',
  },
  'Personal Details accordion collapse click': {
    linkType: 'accordion',
    linkName: 'Personal Details Accordion Collapse',
    StepName: 'Confirm Details',
    linkPosition: 'Form',
  },
  'Personal Details accordion expand click': {
    linkType: 'accordion',
    linkName: 'Personal Details Accordion Expand',
    StepName: 'Confirm Details',
    linkPosition: 'Form',
  },
  'Financial Details accordion collapse click': {
    linkType: 'accordion',
    linkName: 'Financial Details Accordion Collapse',
    StepName: 'Confirm Details',
    linkPosition: 'Form',
  },
  'Financial Details accordion expand click': {
    linkType: 'accordion',
    linkName: 'Financial Details Accordion Expand',
    StepName: 'Confirm Details',
    linkPosition: 'Form',
  },
  'Nominee Details accordion collapse click': {
    linkType: 'accordion',
    linkName: 'Nominee Details Accordion Collapse',
    StepName: 'Confirm Details',
    linkPosition: 'Form',
  },
  'Nominee Details accordion expand click': {
    linkType: 'accordion',
    linkName: 'Nominee Details Accordion Expand',
    StepName: 'Confirm Details',
    linkPosition: 'Form',
  },
  'Nominee Details click': {
    linkType: 'accordion',
    StepName: 'Confirm Details',
    linkPosition: 'Form',
  },
  'Fatca Details click': {
    linkType: 'accordion',
    StepName: 'Confirm Details',
    linkPosition: 'Form',
  },
  'Personal Details click': {
    linkType: 'accordion',
    StepName: 'Confirm Details',
    linkPosition: 'Form',
  },
  'on submit click': {
    linkType: 'button',
    StepName: 'Step 5 - Confirmation',
    linkPosition: 'Form',
  },
  'privacy click': {
    linkType: 'cta',
    linkName: 'privacy click',
    linkPosition: 'Form',
  },
  'requested product click': {
    linkType: 'cta',
    linkName: 'requested product click',
    linkPosition: 'Form',
  },
  'other products click': {
    linkType: 'cta',
    linkName: 'other products click',
    linkPosition: 'Form',
  },
  'apply for click': {
    linkType: 'cta',
    linkName: 'apply for click',
    linkPosition: 'Form',
  },
  'hdfc website click': {
    linkType: 'cta',
    linkName: 'hdfc website click',
    linkPosition: 'Form',
  },
};
const ANALYTICS_CLICK_OBJECT = {
  page: {
    pageInfo: {
      pageName: '',
      errorCode: '',
      errorMessage: '',
    },
  },
  user: {
    pseudoID: '',
    journeyID: '',
    journeyName: '',
    journeyState: '',
    casa: '',
    gender: '',
    email: '',
  },
  form: {
    name: '',
  },
  link: {
    linkName: '',
    linkType: '',
    linkPosition: '',
  },
  assisted: {
    flag: '',
    lg: '',
    lc: '',
  },
  event: {
    phone: '',
    validationMethod: '',
    status: '',
    rating: '',
    mobileWith: '',
    mobileWithPlus: '',
  },
  formDetails: {
    employmentType: '',
    companyName: '',
    designation: '',
    relationshipNumber: '',
    pincode: '',
    city: '',
    state: '',
    KYCVerificationMethod: '',
    languageSelected: '',
    reference: '',
    isVideoKYC: '',
    documentProof: '',
    nomineeRelation: '',
    facingIssue: '',
  },
  card: {
    selectedCard: '',
    eligibleCard: '',
    annualFee: '',
  },
};

const ANALYTICS_PAGE_LOAD_OBJECT = {
  page: {
    pageInfo: {
      pageName: '',
      errorCode: '',
      errorMessage: '',
    },
  },
  user: {
    pseudoID: '',
    journeyID: '',
    journeyName: '',
    journeyState: '',
    casa: '',
    aan: '',
  },
  form: {
    name: '',
  },
  event: {
    authMethod: '',
    mobileWith: '',
    mobileWithPlus: '',
  },
  formDetails: {
    city: '',
    state: '',
    pincode: '',
    nationality: '',
    countryTaxResidence: '',
    countryofBirth: '',
    nomineeRelation: '',
    companyName: '',
    AnnualIncome: '',
    currency: '',
    residenceType: '',
    sourceoffunds: '',
    selfemployeddate: '',
    natureofbusiness: '',
    typeofcompany: '',
    typeofprofessional: '',
    bankBranch: '',
    existingAccountType: '',
    accountType: '',
  },
};

const PAGE_NAME = {
  ccc: {
    'otp click': 'Identify Yourself',
    'confirm otp': 'Verify with OTP',
    'check offers': 'Customer Details',
    'get this card': 'Choose Card',
    'kyc continue': 'Select KYC',
    'i agree': 'Select KYC - Aadhaar Pop-Up',
    'document upload continue': 'Document Upload',
    'address continue': 'Address Details',
    'aadhaar otp': 'Select KYC - Aadhaar OTP verification',
    'start kyc': 'Confirmation',
    'submit review': 'Confirmation',
    'thank you screen': 'Step 5 - Confirmation',
  },
  nrenro: {
    'otp click': 'Step 1 - Identify Yourself',
    'confirm otp': 'Step 2 - Verify with OTP',
    'select account': 'Step 3 - Select  Account',
    'select account type': 'Step 3 - Account Type',
    'confirm details': 'Step 4 - Confirm Details',
    'confirmation page': 'Step 5 - Confirmation',
    'Apply for a CTA Click': 'Step 5 - Confirmation',
    'HDFC Bank Website Link Click': 'Step 5 - Confirmation',
    'check offers': 'Customer Details',
    'get this card': 'Choose Card',
    'kyc continue': 'Select KYC',
    'i agree': 'Select KYC - Aadhaar Pop-Up',
    'document upload continue': 'Document Upload',
    'address continue': 'Address Details',
    'aadhaar otp': 'Select KYC - Aadhaar OTP verification',
    'start kyc': 'Confirmation',
    'submit review': 'Confirmation',
    'thank you screen': 'Step 5 - Confirmation',
    'privacy click': 'Step 1 - Identify Yourself',
    'other products click': 'Step 1 - Identify Yourself',
    'requested product click': 'Step 1 - Identify Yourself',
  },
};
export {
  data,
  ANALYTICS_CLICK_OBJECT,
  ANALYTICS_PAGE_LOAD_OBJECT,
  PAGE_NAME,
};
