const JOURNEY_NAME = 'SMART_EMI_JOURNEY';
const PRO_CODE = '009';
const ERROR_MSG = {
  mobileError: 'Enter valid mobile number',
  noEligibleTxnFlow: 'There are no eligible transactions on this card. Please try a different card.',
};

const FLOWS_ERROR_MESSAGES = {
  XFACE_INQ_VP_0003: 'Hey, it seems like you have entered incorrect details. Request you to check & re-enter your last 4 digits of the card.',
  XFACE_E2FA_02: 'Incorrect OTP code. Please try again.', // For this case error message is hardcoded in rule
  XFACE_E2FA_04: 'Oops! you have entered wrong otp too many times please try again later',
};

const CHANNELS = {
  adobeWeb: 'ADOBE_WEB',
  adobeWhatsApp: 'ADOBE_WHATSAPP',
};

const SEMI_ENDPOINTS = {
  otpGen: 'https://applyonlinedev.hdfcbank.com/content/hdfc_ccforms/api/validatecardotpgen.json',
  otpVal: 'https://applyonlineuat01.hdfcbank.com/content/hdfc_hafcards/api/eligibilitycheck.json',
  preexecution: 'https://applyonlinedev.hdfcbank.com/content/hdfc_ccforms/api/preexecution.json',
  masterChanel: 'https://applyonlinedev.hdfcbank.com/content/hdfc_commonforms/api/mdm.CREDIT.POST_ISSUANCE_CHANNEL_MASTER.json',
  ccSmartEmi: 'https://applyonlinedev.hdfcbank.com/content/hdfc_ccforms/api/ccsmartemi.json',
  branchMaster: 'https://applyonlinedev.hdfcbank.com/content/hdfc_commonforms/api/mdm.CREDIT.POST_ISSUANCE_BRANCH_MASTER.BRANCH_CODE',
  dsaCode: 'https://applyonlinedev.hdfcbank.com/content/hdfc_commonforms/api/mdm.CREDIT.POST_ISSUANCE_DSA_MASTER.DSACODE',
};

const DOM_ELEMENT = {
  semiWizard: 'aem_semiWizard',
  chooseTransaction: 'aem_chooseTransactions',
  selectTenure: 'aem_selectTenure',
};

const MISC = {
  rupeesUnicode: '\u20B9',
};

const OTP_TIMER = 30;
const MAX_OTP_RESEND_COUNT = 3;
const CURRENT_FORM_CONTEXT = {};
const DATA_LIMITS = {
  totalSelectLimit: 10,
  otpTimeLimit: 30,
  maxOtpResendLimit: 3,
};

const RESPONSE_PAYLOAD = {
  response: {
    pseudoID: '{ "ResponseEncryptedValue": "", "GWSymmetricKeyEncryptedValue": "", "Scope": "ADCC", "TransactionId": "AD22102024082940", "Status": "TH99503: API Back-end Service Not Available or Timed-Out"}',
    blockCode: {
      mad: '000000000000000',
      bbvlogn_card_outst: '-00000000267179',
      billingCycle: '05',
      tad: '0000009177400',
      cardNumber: '1011500001058142',
    },
    address: {
      city: 'BENGALURU',
      postalCode: '560066',
      name: 'Vidya Pradeep',
      addressLine1: 'MBRDI',
      addressLine2: 'EMBASSY CREST PLOT NO 5-P',
      addressLine3: 'EPIP ZONE PHASE-1 WHITEFIELD R',
      state: 'KA',
      addressLine4: '',
    },
    ccBilledTxnResponse: {
      responseString: [
        {
          date: '05-03-2021',
          amount: '     3500.00',
          AUTH_CODE: '',
          STS: 'N',
          LOGICMOD: '1',
          name: 'SEMI_WEBB_TESTING_ ELIPLISSIS TXNS FOR SEMISEMI_WEBB_TESTING_ ELIPLISSIS TXNS FOR SEMI ',
          lasttxnseqno: '35',
          id: '40117',
          PLANNO: '10002',
        },
        {
          date: '05-03-2021',
          amount: '     3400.00',
          AUTH_CODE: '',
          STS: 'N',
          LOGICMOD: '1',
          name: 'TXNS FOR SEMI',
          lasttxnseqno: '34',
          id: '40109',
          PLANNO: '10002',
        },
        {
          date: '05-03-2021',
          amount: '     3300.00',
          AUTH_CODE: '',
          STS: 'N',
          LOGICMOD: '1',
          name: 'TXNS FOR SEMI SEMI_WEBB_TESTING_ ELIPLISSIS TXNS FOR SEMI',
          lasttxnseqno: '33',
          id: '40091',
          PLANNO: '10002',
        },
        {
          date: '04-03-2021',
          amount: '     4300.00',
          AUTH_CODE: '',
          STS: 'N',
          LOGICMOD: '1',
          name: '20 UNBILLED TXN',
          lasttxnseqno: '20',
          id: '00180',
          PLANNO: '10002',
        },
        {
          date: '04-03-2021',
          amount: '     4200.00',
          AUTH_CODE: '',
          STS: 'N',
          LOGICMOD: '1',
          name: '20 UNBILLED TXN',
          lasttxnseqno: '19',
          id: '00172',
          PLANNO: '10002',
        },
        {
          date: '04-03-2021',
          amount: '     4100.00',
          AUTH_CODE: '',
          STS: 'N',
          LOGICMOD: '1',
          name: '20 UNBILLED TXN',
          lasttxnseqno: '18',
          id: '00164',
          PLANNO: '10002',
        },
        {
          date: '04-03-2021',
          amount: '     4000.00',
          AUTH_CODE: '',
          STS: 'N',
          LOGICMOD: '1',
          name: '20 UNBILLED TXN',
          lasttxnseqno: '17',
          id: '00156',
          PLANNO: '10002',
        },
        {
          date: '04-03-2021',
          amount: '     2600.00',
          AUTH_CODE: '',
          STS: 'N',
          LOGICMOD: '1',
          name: '20 UNBILLED TXN',
          lasttxnseqno: '3',
          id: '00016',
          PLANNO: '10002',
        },
      ],
      status: {
        errorCode: '0',
        errorMsg: '0',
      },
    },
    responseString: {
      relationNumber: '0001010000000219515',
      primaryCardHolderName: 'Vidya Pradeep',
      records: [
        {
          maxEligibleAmt: '00000000000700000',
          procWaiv2: '00',
          procWaiv4: '00',
          procWaiv3: '00',
          period4: '018',
          period3: '012',
          procWaiv5: '0',
          period2: '006',
          maximumProcessingFee5: '>9999999 99',
          plan: '00000',
          maximumProcessingFee4: '00',
          maximumProcessingFee3: '00',
          period5: '024',
          maximumProcessingFee2: '00',
          period: '003',
          minimumProcessingFee2: '00',
          thresholdAmount5: '000000000000',
          maximumProcessingFeeRedef2: '00',
          minimumProcessingFee4: '00',
          thresholdAmount4: '000000000000',
          minimumProcessingFee3: '00',
          thresholdAmount3: '000000000000',
          processingFeeRedef: '799 00',
          maximumProcessingFeeRedef4: '00',
          maximumProcessingFeeRedef3: '00',
          percentageRedef: '> 00',
          maximumProcessingFeeRedef5: '>9999999 99',
          thresholdAmount2: '000000000000',
          interestX4: '01500',
          minimumProcessingFeeRedef: '00',
          interestX5: '01600',
          minimumProcessingFee5: '00',
          interestX2: '01188',
          interestX3: '02488',
          planDescription: '',
          proCode: '009',
          thresholdAmountRedef2: '000000000000',
          prodId: '00009',
          thresholdAmountRedef4: '000000000000',
          thresholdAmountRedef3: '000000000000',
          thresholdAmountRedef5: '000000000000',
          memoLine1: '499',
          percentage2: '> 00',
          percentage3: '> 00',
          feeWaiverFlg: '0',
          percentage4: '00',
          percentage5: '00',
          memoLine4: 'MEMOLINE004',
          memoLine3: 'MEMOLINE003',
          memoLine2: 'MEMOLINE002',
          plan5: '00000',
          plan2: '00000',
          plan3: '00000',
          plan4: '00000',
          interestR2: '1188',
          interestR3: '2488',
          planDescription5: '',
          planDescription3: '',
          interestR4: '1500',
          planDescription4: '',
          interestR5: '1600',
          planDescription2: '',
          processingFee5: '99 00',
          processingFee4: '799 00',
          processingFee3: '799 00',
          processingFeeRedef3: '799 00',
          thresholdAmountRedef: '000000000000',
          processingFeeRedef4: '799 00',
          processingFeeRedef5: '99 00',
          processingFee: '799 00',
          tid: '000000106',
          processingFeeRedef2: '00',
          interestO: '0',
          minimumProcessingFee: '00',
          percentage: '> 00',
          logo: '000',
          interestX: '03088',
          prodDesc: 'SMART EMI DIAL AN EMI',
          interestR: '3088',
          eligibleAmtPercent: 'A',
          tid5: '000000192',
          tid3: '000000109',
          tid4: '000000113',
          tid2: '000000102',
          processingFee2: '00',
          interest3: '02488',
          interest2: '01188',
          interest5: '01600',
          interest4: '01500',
          maximumProcessingFee: '00',
          percentageRedef3: '> 00',
          encryptedToken: '[B@12a3a380TMDAwMTAxMTUwMDAwMTA1ODE0MjAwMDAwMDAwMDAwMDAwMDA=',
          percentageRedef2: '> 00',
          logo2: '000',
          interestO5: '0',
          maximumProcessingFeeRedef: '00',
          minimumProcessingFeeRedef5: '00',
          percentageRedef5: '00',
          percentageRedef4: '00',
          minimumProcessingFeeRedef2: '00',
          minimumProcessingFeeRedef3: '00',
          minimumProcessingFeeRedef4: '00',
          logo4: '000',
          logo3: '000',
          procWaivredef5: '0',
          logo5: '000',
          procWaivredef2: '00',
          procWaivredef4: '00',
          procWaivredef3: '00',
          interest: '03088',
          eligible: 'Y',
          eligibleAmt: '00000000000700000',
          interestO3: '0',
          interestO4: '0',
          interestO2: '0',
          thresholdAmount: '000000000000',
          savingAcctNumber: '0000000000000000',
          processingFeeFlag: 'F',
          processingFeeFlag4: 'F',
          processingFeeFlag3: 'F',
          processingFeeFlag5: 'F',
          procWaiv: '00',
          processingFeeFlag2: 'P',
        },
      ],
      custNumber: '0001011500001058142',
      creditLimit: '000200000',
      aanNumber: '0001011500001058142',
    },
    cardHolderName: 'Vidya Pradeep',
    ccUnBilledTxnResponse: {
      responseString: [
        {
          date: '06-03-2021',
          authcode: '',
          amount: ' 00000000380000',
          STS: 'N',
          LOGICMOD: '01',
          name: 'TXNS UNBILLED TXNS UNBILLEDTXNS UNBILLED TXNS UNBILLED                          ',
          lasttxnseqno: '00015',
          id: '70146 ',
          PLANNO: '10002',
        },
        {
          date: '06-03-2021',
          authcode: '',
          amount: ' 00000000370000',
          STS: 'N',
          LOGICMOD: '01',
          name: 'TXNS UNBILLED      TXNS UNBILLED222                     ',
          lasttxnseqno: '00014',
          id: '70138 ',
          PLANNO: '10002',
        },
        {
          date: '06-03-2021',
          authcode: '',
          amount: ' 00000000340000',
          STS: 'N',
          LOGICMOD: '01',
          name: 'TXNS UNBILLED  SERVICE lIMITED TXNS UNBILLEDTXNS UNBILLED                         ',
          lasttxnseqno: '00011',
          id: '70104 ',
          PLANNO: '10002',
        },
        {
          date: '06-03-2021',
          authcode: '',
          amount: ' 00000000250000',
          STS: 'N',
          LOGICMOD: '01',
          name: 'TXNS UNBILLED                           ',
          lasttxnseqno: '00002',
          id: '70013 ',
          PLANNO: '10002',
        },
      ],
      status: {
        errorCode: '00000',
        lasttxnseqno: '13',
        errorMsg: '0',
      },
    },
    cardTypePath: '/content/dam/hdfc/cc-forms/card_facia/11-HdfcIocl-Visa.jpg',
    productDetails: {
      currentCardDetails: {
        features: {
          'Catalogue – Redemption (up to)': 'NA',
          'Flight & Hotel – Redemption': 'NA',
          'International Lounge Access/Year': 'NA',
          'Cashback – Redemption': 'NA',
          'Domestic Lounge Access/year': 'NA',
          'Reward Points / Rs150 spent': 'NA',
        },
        PRODUCT: 'SNAP DEAL CO_BRAND',
        cardType: 'Visa',
        verticalcard: '',
        cardTypePath: '/content/dam/hdfc/cc-forms/card_facia/18-SnapDealCo_Brand-Visa.jpg',
      },
      showLinkFlag: 'false',
    },
    email: {
      residenceEmail: 'vidya.pradeep@hdfcbank.com',
      officeEmail: 'vidya.pradeep@hdfcbank.com',
    },
    status: {
      errorCode: '0',
      errorMsg: 'Success',
    },
  },
};
export {
  JOURNEY_NAME,
  ERROR_MSG,
  OTP_TIMER,
  SEMI_ENDPOINTS,
  MAX_OTP_RESEND_COUNT,
  CURRENT_FORM_CONTEXT,
  CHANNELS,
  PRO_CODE,
  DOM_ELEMENT,
  MISC,
  DATA_LIMITS,
  FLOWS_ERROR_MESSAGES,
  RESPONSE_PAYLOAD,
};
