import { CURRENT_FORM_CONTEXT } from '../../common/constants.js';

const { customerInfo } = CURRENT_FORM_CONTEXT;
const createExecuteInterfaceRequest = (payload, globals) => {
  const { reviewDetailsView } = globals.form.fdBasedCreditCardWizard.basicDetails;
  const { personalDetails, addressDetails } = reviewDetailsView;
  const request = {
    requestString: {
      bankEmployee: 'N',
      mobileNumber: globals.form.loginMainPanel.loginPanel.mobilePanel.registeredMobileNumber.$value,
      fullName: customerInfo?.customerFullName,
      panCheckFlag: 'Y',
      perAddressType: '2',
      personalEmailId: personalDetails?.emailID,
      selfConfirmation: 'Y',
      addressEditFlag: addressDetails?.mailingAddressToggle?.$value === 'on' ? 'N' : 'Y',
      communicationAddress1: 'I THINK LODHA FLAT NO 93',
      communicationAddress2: 'COURTYARD MUMBAI',
      communicationCity: 'Mumbai',
      dateOfBirth: '20020218',
      firstName: 'Ranjit',
      lastName: 'Vijay',
      gender: '1',
      occupation: '1',
      officialEmailId: 'deepak.bisht@hdfcbank.com',
      panEditFlag: 'N',
      panNumber: 'OJSPS6821J',
      permanentAddress1: 'I THINK LODHA FLAT NO 93',
      permanentAddress2: 'COURTYARD MUMBAI',
      permanentCity: 'Mumbai',
      permanentZipCode: '400042',
      eReferenceNumber: 'AD20240826120139101',
      nameEditFlag: 'Y',
      mobileEditFlag: 'N',
      resPhoneEditFlag: 'N',
      comAddressType: '2',
      comCityZip: '400042',
      customerID: 'XXXXX7890',
      timeInfo: '2024-08-06T05:39:55.021Z',
      communicationAddress3: '',
      permanentAddress3: '',
      officeAddress1: 'off add 1',
      officeAddress2: 'off add 2',
      officeAddress3: null,
      officeCity: 'HYDERABAD',
      officeZipCode: '500019',
      officeState: 'Telangana',
      productCode: '',
      leadClosures: 'R2432',
      leadGenerater: '34234',
      applyingBranch: 'N',
      smCode: '',
      dseCode: '',
      lc2: '2323',
      filler6: '',
      branchName: '',
      branchCity: '',
      companyName: 'HDFC Bank',
      departmentOrEmpCode: 'D11434',
      designation: 'AVP',
      middleName: 'SO',
      perfiosTxnID: '',
      monthlyincome: '',
      annualItr: '',
      permanentState: 'MAHARASHTRA',
      communicationState: 'MAHARASHTRA',
      authMode: '',
      journeyID: 'f04317f0-b484-4ec5-9d9a-b43f3e3d06bf_01_aa_a_bb',
      journeyName: 'CORPORATE_CARD_JOURNEY',
      nameOnCard: 'RANJIT SO VIJAY',
      dsaValue: '',
      cardsData: '',
      channelSource: '',
      isManualFlow: 'false',
      channel: '',
      apsDobEditFlag: 'N',
      apsEmailEditFlag: 'N',
      journeyFlag: 'ETB',
      annualIncomeOrItrAmount: '100000',
      comResidenceType: '2',
      CCAD_Relationship_number: '20045266',
    },
  };
  return request;
};

const executeInterface = (payload, globals) => {
  const executeInterfaceRequest = createExecuteInterfaceRequest(payload, globals);
};

export default executeInterface;
